version: "3.2"
services:
  api:
    image: flask_api
    container_name: flask_api
    build:
      context: ./src
    ports:
      - "5010:5010"
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    
  consumer:
    image: flask_consumer
    container_name: flask_consumer
    build:
      context: ./consumer
    ports:
      - "5011:5011"
    depends_on:
      - redis

