version: "3.2"
services:
  producer:
    image: producer
    container_name: producer
    build:
      context: ./producer
    ports:
      - "5010:5010"
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    
  consumer:
    image: consumer
    container_name: consumer
    build:
      context: ./consumer
    ports:
      - "5011:5011"
    depends_on:
      - redis

